### PR TITLE
Fix for #49 - always load iframe scripts before compiling javascript 

### LINKED ISSUE #49: target-platform js indefinite loading with js-libs
Multiple `target-platform="js"` playgrounds with different `data-js-libs` on one page don't execute properly. Some of them keep loading indefinitely.

In this example, the second one is broken.
http://www.redsource.at/playground/kotlin-playground-js-js-libs.html

### PR DESCRIPTION
**Pull request by fgutmann**
Until now loading iframe scripts used two different strategies depending
on target platform.

- For canvas it was loaded just before compiling to javascript.
- For js it was loaded on page load and then reloaded after every
execution.

Since all js executable-fragments share the same iframe for one kotlin
version, there were problems when two executable-fragments used
different data-js-libs.

Javascript libs were loaded for the very first executable fragment on the page.
On execution nothing was reloaded. Subsequent fragments on the page that used
different data-js-libs than the first one were therefore broken.

The new implementation loads iframe scripts just before compiling to
javascript, no matter which js platform is used. This ensures that the
correct js-libs are loaded when the code is ready to execute.

However there are still some open issues with sharing one iframe for
multiple executable fragments. Errors occur when two fragments run in
parallel. In the best case one will be killed. In the worst case we have
a race condition and still have the wrong data-js-libs loaded.

Fixes #49

### CODE REVIEW

**Comment by AlexanderPrendota** [comment]
Hi! Thank you for PR. Let's discuss it:
1) Please take a look on method `getNodeForMountIframe`. If you want to have 1 iframe on each editor you always have to use `this.nodes[0].querySelector(SELECTORS.CANVAS_PLACEHOLDER_OUTPUT);`. What do u think about it?
2) If you want to have 1 iframe you dot need to store executors in `const jsExecutors = new Map();` I guess 🙂

3) Did you test your solution on 1 page with 3 editors with different Kotlin version?
4) Did you test snippets on slow internet connection (slow 3G)? 

Thanks. 😊I'm waiting for your answer.

**Comment by fgutmann** [comment]
Hi Alex!

I fully agree on your points 1 and 2.

The only difference between canvas and js will be the visibility of the iframe handled in `executeJsCode`.

Actually we could remove `TargetPlatform.CANVAS` altogether. We can just use the `data-output-height` attribute to define the visibility of the iframe. Anything non-zero shows it, everything else hides it. This would obviously be an API-breaking change though, so we have to keep that for the next major version.

I will update the PR with the switch to the one iframe version and make sure to test your points 3 and 4.

**Comment by fgutmann** [comment]
@AlexanderPrendota Do you mind if I rebase this branch on the new master?

**Comment by fgutmann** [comment]
@AlexanderPrendota Ready for review again :-)

Testing with Kotlin 1.1 and 1.2 took me some time until I remembered that parameterless `main` wasn't supported back then ;-) Also tested with "mid tier mobile" and "low end mobile" connection speed simulation in Chrome.

**Comment by AlexanderPrendota** [comment]
Hey! Thanks for comment =)
Yes, please rebase on the master. It should help with resolving conflicts.
So, I will have a look at your solution again)

**Comment by fgutmann** [comment]
It's based on current master branch now.

File: src/js-executor/index.js [hunk 1]
```diff
@@ -1,41 +1,23 @@
 import './index.scss'
-import Map from 'es6-map/polyfill';
```
Comment (AlexanderPrendota) [inline src/js-executor/index.js]: Do we need `es6-map/polyfill` anywhere? If not -> `$ yarn remove es6-map/polyfill`

Comment (fgutmann) [reply src/js-executor/index.js]: It's removed now.

The `yarn.lock` file changed quite a lot, since it wasn't updated last time when we changed the babel version (https://github.com/JetBrains/kotlin-playground/pull/48/commits/275d27e10ce5120528871bed00ae1ed527f6b5bf). I didn't realise that a yarn.lock is checked-in back then and used npm.

Is yarn the recommended way to manage dependencies for this project? Then we should probably update the parts of the readme that refer to `npm`. If I used yarn from the beginning, the babel version change would not have been needed at all 😊

Comment (AlexanderPrendota) [reply src/js-executor/index.js]: Yes, I always use `yarn` :)
Ah. Yes, I'll update. Thanks a lot!

**Comment by AlexanderPrendota** [comment]
So, LGTM.
I need to test your solution on my side if all is fine I'll merge this PR and bump a new playground version 🙂

**Comment by fgutmann** [comment]
Great! Thanks for your reviews :-)
Looking forward for the new version.
